app/user/models.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from app.extensions import db, login


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"<User {self.username}>"

app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")
    remember_me = BooleanField("Remember Me")


class RegistrationForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Register")

app/__init__.py
import dash
from flask import Flask
from flask.helpers import get_root_path
from flask_login import login_required
import dash_bootstrap_components as dbc

from config import BaseConfig


def create_app():
    server = Flask(__name__)
    server.config.from_object(BaseConfig)

    register_dashapps(server)
    register_extensions(server)
    register_blueprints(server)

    return server


def register_dashapps(app):
    from app.dashapp1.layout import layout
    from app.dashapp1.callbacks import register_callbacks

    # Meta tags for viewport responsiveness
    meta_viewport = {
        "name": "viewport",
        "content": "width=device-width, initial-scale=1, shrink-to-fit=no",
    }
    dbc_css = (
        "https://cdn.jsdelivr.net/gh/AnnMarieW/dash-bootstrap-templates/dbc.min.css"
    )

    dashapp1 = dash.Dash(
        __name__,
        server=app,
        url_base_pathname="/dashboard-users/",
        assets_folder=get_root_path(__name__) + "/static/assets",
        meta_tags=[meta_viewport],
        external_stylesheets=[dbc.themes.CYBORG, dbc_css, dbc.icons.FONT_AWESOME],
        suppress_callback_exceptions=True,
    )

    with app.app_context():
        dashapp1.title = "Roadr Dash-Board"
        dashapp1.layout = layout
        register_callbacks(dashapp1)

    _protect_dashviews(dashapp1)


def _protect_dashviews(dashapp):
    for view_func in dashapp.server.view_functions:
        if view_func.startswith(dashapp.config.url_base_pathname):
            dashapp.server.view_functions[view_func] = login_required(
                dashapp.server.view_functions[view_func]
            )


def register_extensions(server):
    from app.extensions import db
    from app.extensions import login
    from app.extensions import migrate

    db.init_app(server)
    login.init_app(server)
    login.login_view = "main.login"
    migrate.init_app(server, db)


def register_blueprints(server):
    from app.user.views import server_bp

    server.register_blueprint(server_bp)

app/user/views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.urls import url_parse

from app.extensions import db
from app.user.forms import LoginForm, RegistrationForm
from app.user.models import User

server_bp = Blueprint("main", __name__)


@server_bp.route("/")
def index():
    return render_template("index.html", title="Home Page")


@server_bp.route("/login/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("/dashboard-users/"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            error = "Invalid username or password"
            return render_template("login.html", form=form, error=error)

        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("/dashboard-users/")
        return redirect(next_page)

    return render_template("login.html", title="Sign In", form=form)


@server_bp.route("/logout/")
@login_required
def logout():
    logout_user()

    return redirect(url_for("main.index"))


@server_bp.route("/register/", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("/dashboard-users/"))

    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()

        return redirect(url_for("main.login"))

    return render_template("register.html", title="Register", form=form)

app/templates/base.html
<div>
  Test:
  <a href="{{ url_for('main.index') }}">Home</a>
  {% if current_user.is_anonymous %}
  <a href="{{ url_for('main.login') }}">Login</a>
  {% else %}
  <a href="{{ url_for('main.logout') }}">Logout</a>
  {% endif %}

  {% block content %}
  {% endblock %}
</div>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
{% if current_user.is_anonymous %}
  <h1>Hello, stranger!</h1>
{% else  %}
  <h1>Hi, {{ current_user.username }}!</h1>
  <a href="{{ url_for('/dashboard-users/') }}">Go to the Dashboard</a>
{% endif %}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>
<form action="" method="post" novalidate>
  {{ form.hidden_tag() }}
  <p>
    {{ form.username.label }}<br>
    {{ form.username(size=32) }}<br>
  </p>
  <p>
    {{ form.password.label }}<br>
    {{ form.password(size=32) }}<br>
  </p>
  <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
  <p>{{ form.submit() }}</p>
  {% if error %}
  <p class="error"><strong>Error:</strong> {{ error }}
    {% endif %}
</form>
<p> New User? <a href="{{ url_for('main.register') }}">Click to Register!</a></p>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Signup</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}